services:
  db:
    image: postgres:15-alpine
    container_name: library_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: library_backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/library_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      APP_CORS_ALLOWED_ORIGINS: "http://localhost:5173"

  frontend:
    build: ./library-frontend
    container_name: library_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./library-frontend:/app
      - /app/node_modules

volumes:
  postgres_data: